### ISSUE TITLE
Should everything be under /src?

### ISSUE THREAD

**Issue by alexwilson** [aceew/aws-lambda-response#3]
I'm not sure if there's a good convention on this, but to me it's a little strange that everything is under /src (I naturally went to npm install, and it didn't work - then I realised I should have done it beneath src)

**Comment by aceew** [comment]
Thanks for the advice but I personally think it's generally better practice to have ES6 code in a `src/` folder and have the compiled code that is published to npm within a `dist/`folder. Therefore will not fix.

**Comment by alexwilson** [comment]
Yes but how about the package.json?  Surely we should also commit a dist?

**Comment by aceew** [comment]
Hi,
Yeah, the package.json is in the src folder with the rest of the uncompiled package. My eventual plan is to run the compilation in Travis CI to build the dist folder and also run the deployment from there. I don't think it's a great idea to commit the build folder at all as it should be generated when all the tests pass and then only. If you plan on working on the project please work from within the src folder. This will then be compiled when the version is published to npm.
