### ISSUE TITLE
Manage other attributes (headers, Base64 encoding)

### ISSUE THREAD

**Issue by lmammino** [aceew/aws-lambda-response#7]
Aside from `statusCode` and `body`, it would be nice to have an easy abstraction to manage other attributes of the response object like:

  - `headers`
  - `isBase64Encoded`

As far as I can tell, there is no current capability for it. Am I missing something?

**Comment by aceew** [comment]
Hi @lmammino,
You are correct, there's no capability for it right now. I worked on this package before AWS added Lambda proxy requests, so this was really just used for sending data to gateway and then mapping any data from there.

I think it would be good to have this project work for proxy requests with the features that you've mentioned so I'll leave this open and pick it up when I get the chance.

Thanks

**Comment by lmammino** [comment]
Thanks for your quick reply @aceew!

Meanwhile, I found this project [lambda-proxy-response](https://www.npmjs.com/package/lambda-proxy-response) by @themyth92 that seems to be closer to what I was looking for.

Maybe an action to close this issue can be just adding a reference to this module in the README for people that are using the lambda-proxy integration.
